model:
  name: 'vit_b_16'

data:
  type: 'image'
  root: 'datasets' # SoccerNet train/test/valid/challenge sets will be downloaded under '/path/to/project/datasets/soccernetv3/reid/'
  height: 224
  width: 224
  workers: 4
  sources: ['soccernetv3']
  targets: ['soccernetv3', 'soccernetv3_test'] #, 'soccernetv3_challenge']
#  transforms: ['random_flip', 'random_crop', 'random_patch', 'random_erase']
  # training and validation sets are in the 'soccernetv3' dataset
  # test set is in the 'soccernetv3_test' dataset
  # challenge set is in the 'soccernetv3_challenge' dataset
soccernetv3:
  training_subset: 0.4 #1.0 # train model on 1% of training set samples

sampler:
  train_sampler: RandomIdentitySampler
  train_sampler_t: RandomIdentitySampler
  num_instances: 4

loss:
  name: 'triplet'
  softmax:
    label_smooth: True
  triplet:
    margin: 0.5
    weight_t: 0.9
    weight_x: 0.5
    weight_tc: 0.0
    weight_cc: 0.5
    topk: 1
    bottomk: 1

train:
  batch_size: 192
  print_freq: 10
  max_epoch: 50
  lr: 5e-05 #5.0e-04
  lr_scheduler: 'cosine'
  min_lr: 1.0e-6 #5.0e-5
  optim: 'adam'
  warmup_lr: 1.0e-5
  warmup_steps: 300 #1000
  weight_decay: 0.0005
test:
  ranks: [1]
  export_ranking_results: True # export ranking result to JSON file for external evaluation
